version: "3.9"
services:
  client:
    container_name: cnt-pixelart-client
    restart: always
    build: ./client
    ports: 
      - "3000:3000"
    links:
      - app
  app:
    container_name: cnt-pixelart-api
    restart: always
    build: ./api
    ports:
      - "4000:4000"


